//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace EmailScheduler.Implementation
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EmailRequestEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EmailRequestEntities object using the connection string found in the 'EmailRequestEntities' section of the application configuration file.
        /// </summary>
        public EmailRequestEntities() : base("name=EmailRequestEntities", "EmailRequestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EmailRequestEntities object.
        /// </summary>
        public EmailRequestEntities(string connectionString) : base(connectionString, "EmailRequestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EmailRequestEntities object.
        /// </summary>
        public EmailRequestEntities(EntityConnection connection) : base(connection, "EmailRequestEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="id">No Metadata Documentation available.</param>
        /// <param name="message">No Metadata Documentation available.</param>
        public int EmailRequest_Error(Nullable<global::System.Guid> id, global::System.String message)
        {
            ObjectParameter idParameter;
            if (id.HasValue)
            {
                idParameter = new ObjectParameter("Id", id);
            }
            else
            {
                idParameter = new ObjectParameter("Id", typeof(global::System.Guid));
            }
    
            ObjectParameter messageParameter;
            if (message != null)
            {
                messageParameter = new ObjectParameter("Message", message);
            }
            else
            {
                messageParameter = new ObjectParameter("Message", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("EmailRequest_Error", idParameter, messageParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="id">No Metadata Documentation available.</param>
        /// <param name="scheduleUnitId">No Metadata Documentation available.</param>
        public int EmailRequest_Success(Nullable<global::System.Guid> id, Nullable<global::System.Int32> scheduleUnitId)
        {
            ObjectParameter idParameter;
            if (id.HasValue)
            {
                idParameter = new ObjectParameter("Id", id);
            }
            else
            {
                idParameter = new ObjectParameter("Id", typeof(global::System.Guid));
            }
    
            ObjectParameter scheduleUnitIdParameter;
            if (scheduleUnitId.HasValue)
            {
                scheduleUnitIdParameter = new ObjectParameter("ScheduleUnitId", scheduleUnitId);
            }
            else
            {
                scheduleUnitIdParameter = new ObjectParameter("ScheduleUnitId", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("EmailRequest_Success", idParameter, scheduleUnitIdParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<EmailRequestResult> EmailRequest_Read_Daily()
        {
            return base.ExecuteFunction<EmailRequestResult>("EmailRequest_Read_Daily");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<EmailRequestResult> EmailRequest_Read_Date()
        {
            return base.ExecuteFunction<EmailRequestResult>("EmailRequest_Read_Date");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<EmailRequestResult> EmailRequest_Read_Hourly()
        {
            return base.ExecuteFunction<EmailRequestResult>("EmailRequest_Read_Hourly");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<EmailRequestResult> EmailRequest_Read_Monthly()
        {
            return base.ExecuteFunction<EmailRequestResult>("EmailRequest_Read_Monthly");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<EmailRequestResult> EmailRequest_Read_Weekly()
        {
            return base.ExecuteFunction<EmailRequestResult>("EmailRequest_Read_Weekly");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<EmailRequestResult> EmailRequest_Read_Yearly()
        {
            return base.ExecuteFunction<EmailRequestResult>("EmailRequest_Read_Yearly");
        }

        #endregion
    }
    

    #endregion
    
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="EmailRequest", Name="EmailRequestResult")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class EmailRequestResult : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EmailRequestResult object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="toList">Initial value of the ToList property.</param>
        /// <param name="emailSubject">Initial value of the EmailSubject property.</param>
        /// <param name="emailStatus">Initial value of the EmailStatus property.</param>
        /// <param name="scheduleUnitId">Initial value of the ScheduleUnitId property.</param>
        /// <param name="scheduleOn">Initial value of the ScheduleOn property.</param>
        public static EmailRequestResult CreateEmailRequestResult(global::System.Guid id, global::System.String toList, global::System.String emailSubject, global::System.Int32 emailStatus, global::System.Int32 scheduleUnitId, global::System.String scheduleOn)
        {
            EmailRequestResult emailRequestResult = new EmailRequestResult();
            emailRequestResult.Id = id;
            emailRequestResult.ToList = toList;
            emailRequestResult.EmailSubject = emailSubject;
            emailRequestResult.EmailStatus = emailStatus;
            emailRequestResult.ScheduleUnitId = scheduleUnitId;
            emailRequestResult.ScheduleOn = scheduleOn;
            return emailRequestResult;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ToList
        {
            get
            {
                return _ToList;
            }
            set
            {
                OnToListChanging(value);
                ReportPropertyChanging("ToList");
                _ToList = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ToList");
                OnToListChanged();
            }
        }
        private global::System.String _ToList;
        partial void OnToListChanging(global::System.String value);
        partial void OnToListChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailSubject
        {
            get
            {
                return _EmailSubject;
            }
            set
            {
                OnEmailSubjectChanging(value);
                ReportPropertyChanging("EmailSubject");
                _EmailSubject = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailSubject");
                OnEmailSubjectChanged();
            }
        }
        private global::System.String _EmailSubject;
        partial void OnEmailSubjectChanging(global::System.String value);
        partial void OnEmailSubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailBody
        {
            get
            {
                return _EmailBody;
            }
            set
            {
                OnEmailBodyChanging(value);
                ReportPropertyChanging("EmailBody");
                _EmailBody = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailBody");
                OnEmailBodyChanged();
            }
        }
        private global::System.String _EmailBody;
        partial void OnEmailBodyChanging(global::System.String value);
        partial void OnEmailBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmailStatus
        {
            get
            {
                return _EmailStatus;
            }
            set
            {
                OnEmailStatusChanging(value);
                ReportPropertyChanging("EmailStatus");
                _EmailStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmailStatus");
                OnEmailStatusChanged();
            }
        }
        private global::System.Int32 _EmailStatus;
        partial void OnEmailStatusChanging(global::System.Int32 value);
        partial void OnEmailStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> RequestedBy
        {
            get
            {
                return _RequestedBy;
            }
            set
            {
                OnRequestedByChanging(value);
                ReportPropertyChanging("RequestedBy");
                _RequestedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RequestedBy");
                OnRequestedByChanged();
            }
        }
        private Nullable<global::System.Guid> _RequestedBy;
        partial void OnRequestedByChanging(Nullable<global::System.Guid> value);
        partial void OnRequestedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                OnCreateDateChanging(value);
                ReportPropertyChanging("CreateDate");
                _CreateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateDate");
                OnCreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateDate;
        partial void OnCreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateDate
        {
            get
            {
                return _UpdateDate;
            }
            set
            {
                OnUpdateDateChanging(value);
                ReportPropertyChanging("UpdateDate");
                _UpdateDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateDate");
                OnUpdateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateDate;
        partial void OnUpdateDateChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ScheduleUnitId
        {
            get
            {
                return _ScheduleUnitId;
            }
            set
            {
                OnScheduleUnitIdChanging(value);
                ReportPropertyChanging("ScheduleUnitId");
                _ScheduleUnitId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ScheduleUnitId");
                OnScheduleUnitIdChanged();
            }
        }
        private global::System.Int32 _ScheduleUnitId;
        partial void OnScheduleUnitIdChanging(global::System.Int32 value);
        partial void OnScheduleUnitIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ScheduleOn
        {
            get
            {
                return _ScheduleOn;
            }
            set
            {
                OnScheduleOnChanging(value);
                ReportPropertyChanging("ScheduleOn");
                _ScheduleOn = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ScheduleOn");
                OnScheduleOnChanged();
            }
        }
        private global::System.String _ScheduleOn;
        partial void OnScheduleOnChanging(global::System.String value);
        partial void OnScheduleOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AttachmentList
        {
            get
            {
                return _AttachmentList;
            }
            set
            {
                OnAttachmentListChanging(value);
                ReportPropertyChanging("AttachmentList");
                _AttachmentList = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AttachmentList");
                OnAttachmentListChanged();
            }
        }
        private global::System.String _AttachmentList;
        partial void OnAttachmentListChanging(global::System.String value);
        partial void OnAttachmentListChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TrialCount
        {
            get
            {
                return _TrialCount;
            }
            set
            {
                OnTrialCountChanging(value);
                ReportPropertyChanging("TrialCount");
                _TrialCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TrialCount");
                OnTrialCountChanged();
            }
        }
        private Nullable<global::System.Int32> _TrialCount;
        partial void OnTrialCountChanging(Nullable<global::System.Int32> value);
        partial void OnTrialCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RepeatCount
        {
            get
            {
                return _RepeatCount;
            }
            set
            {
                OnRepeatCountChanging(value);
                ReportPropertyChanging("RepeatCount");
                _RepeatCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RepeatCount");
                OnRepeatCountChanged();
            }
        }
        private Nullable<global::System.Int32> _RepeatCount;
        partial void OnRepeatCountChanging(Nullable<global::System.Int32> value);
        partial void OnRepeatCountChanged();

        #endregion
    }

    #endregion
    
}
